#!/home/alchemmist/.cache/pypoetry/virtualenvs/weather-cli-Nuvw6qni-py3.11/bin/python3


from interface import init_interface, parser, processing_args


def main():
    init_interface()

    args = parser.parse_args()
    processing_args(args)


if __name__ == "__main__":
    main()
